apiVersion: v1
kind: Service
metadata:
  name: hytale-server
  namespace: hytale
spec:
  selector:
    app: hytale
    role: server
  type: NodePort
  ports:
    - name: hytale-udp
      port: 5520
      targetPort: 5520
      protocol: UDP
      nodePort: 31520
